engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript

ratings:
  paths:
    - "src/**"

exclude_paths:
  - "**/examples/"
  - "**/build/"
  - "**/docs/"
  - "**/tests/"
  - "**/*.d.ts"
